language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

sudo: false

matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR

install:
  - cpanm --quiet --notest Devel::Cover::Report::Coveralls
  - cpanm --quiet --notest --installdep

script:
  - perl Makefile.PL
  - make
  - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -b -r -s t
  - cover

after_success:
  - cover -report coveralls

branches:
  only:
    - master
    # - upstream
